name: nbehbc
channels:
- defaults
dependencies:
- python=3.6
- pip
- numpy
- scipy
- matplotlib
- vtk>=8
- pip:
  - mne
  - "https://github.com/wmvanvliet/conpy/zipball/master"
  - "https://github.com/enthought/traits/zipball/a7a83182048c08923953e302658b51b68c802132"
  - "https://github.com/enthought/pyface/zipball/13a064de48adda3c880350545717d8cf8929afad"
  - "https://github.com/enthought/traitsui/zipball/ee8ef0a34dfc1db18a8e2c0301cc18d96b7a3e2f"
  - "https://github.com/wmvanvliet/mayavi/zipball/master"
  - "https://github.com/nipy/PySurfer/zipball/master"
